In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# MAKING DATASET

movie = pd.read_csv('/content/tmdb_5000_movies.csv')
users = pd.read_csv('/content/Users.csv')
ratings = pd.read_csv('/content/Ratings.csv')

In [ ]:
movie.shape

(4803, 20)

In [ ]:
import numpy as np
import pandas as pd

# MAKING DATASET

In [ ]:
movies = pd.read_csv('/content/tmdb_5000_movies.csv')
users = pd.read_csv('/content/Users.csv')
ratings = pd.read_csv('/content/Ratings.csv')

In [ ]:
ratings.head(2)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [ ]:
users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [ ]:
user_ratings = ratings.merge(users, left_on='User-ID', right_on='User-ID')

user_ratings.head()

   User-ID        ISBN  Book-Rating                       Location   Age
0   276725  034545104X            0              tyler, texas, usa   NaN
1   276726  0155061224            5       seattle, washington, usa   NaN
2   276727  0446520802            0  h, new south wales, australia  16.0
3   276729  052165615X            3           rijeka, n/a, croatia  16.0
4   276729  0521795028            6           rijeka, n/a, croatia  16.0

In [ ]:
import random
# Assume movie['id'] is a Series of movie IDs
movie_ids = movies['id'].tolist()

# Replace ISBN with random movie ID
user_ratings['movie_id'] = [random.choice(movie_ids) for _ in range(len(user_ratings))]

# Optionally drop the ISBN column if it's no longer needed
user_ratings = user_ratings.drop(columns=['ISBN'])

In [ ]:
user_ratings.head()

   User-ID  Book-Rating                       Location   Age  movie_id
0   276725            0              tyler, texas, usa   NaN      5689
1   276726            5       seattle, washington, usa   NaN      8849
2   276727            0  h, new south wales, australia  16.0     17820
3   276729            3           rijeka, n/a, croatia  16.0      6519
4   276729            6           rijeka, n/a, croatia  16.0     11013

In [ ]:
movie.rename(columns={'id': 'movie_id'}, inplace=True)

In [ ]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [ ]:
movies.duplicated().sum()

np.int64(0)

# POPULARITY BASED RECOMENDATION

THE MOST POPULAR 20 MOVIES

In [ ]:
# Ensure the movies dataframe has the 'movie_id' column by renaming 'id'
movies.rename(columns={'id': 'movie_id'}, inplace=True)

# Now perform the merge operation
merged = user_ratings.merge(movies, on='movie_id', how='left')

In [ ]:
merged.head()

,User-ID,Book-Rating,Location,Age,movie_id,budget,genres,homepage,keywords,original_language,...,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,276725,0,"tyler, texas, usa",NaN,5689,4500000,"[{""id"": 10749, ""name"": ""Romance""}, {""id"": 12, ...",NaN,"[{""id"": 566, ""name"": ""sexual identity""}, {""id""...",en,...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1980-07-05,58853106,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A sensuous story of natural love.,The Blue Lagoon,5.8,408
1,276726,5,"seattle, washington, usa",NaN,8849,60000000,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,"[{""id"": 242, ""name"": ""new york""}, {""id"": 1332,...",en,...,"[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2004-10-22,13395939,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Meet a man who never met a woman he didn't love.,Alfie,5.6,248
2,276727,0,"h, new south wales, australia",16.0,17820,2300000,"[{""id"": 10402, ""name"": ""Music""}, {""id"": 10749,...",NaN,"[{""id"": 4344, ""name"": ""musical""}, {""id"": 5987,...",en,...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1951-07-13,11000000,107.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,It's NEW!,Show Boat,6.9,18
3,276729,3,"rijeka, n/a, croatia",16.0,6519,50000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.warnerbros.com/dukes-hazzard/index_...,"[{""id"": 798, ""name"": ""sheriff""}, {""id"": 4932, ...",en,...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,110803676,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Cousins. Outlaws. Thrillbillies.,The Dukes of Hazzard,5.1,316
4,276729,6,"rijeka, n/a, croatia",16.0,11013,4000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,"[{""id"": 236, ""name"": ""suicide""}, {""id"": 1443, ...",en,...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2002-01-11,9304609,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Assume the position.,Secretary,6.7,376

In [ ]:
movie_ratings = merged[['User-ID','Book-Rating','Location','Age','movie_id','title']]

In [ ]:
movie_ratings.head(1)

   User-ID  Book-Rating           Location  Age  movie_id            title
0   276725            0  tyler, texas, usa  NaN      5689  The Blue Lagoon

In [ ]:
movie_ratings.groupby('title').count()

                            User-ID  Book-Rating  Location  Age  movie_id
title
#Horror                         230          230       230  172       230
(500) Days of Summer            239          239       239  183       239
10 Cloverfield Lane             261          261       261  187       261
10 Days in a Madhouse           254          254       254  187       254
10 Things I Hate About You      252          252       252  184       252
...                             ...          ...       ...  ...       ...
[REC]²                          253          253       253  181       253
eXistenZ                        240          240       240  173       240
xXx                             235          235       235  175       235
xXx: State of the Union         245          245       245  177       245
Æon Flux                        219          219       219  160       219

[4800 rows x 5 columns]

In [ ]:
# Count number of ratings per movie title
movie_rating_counts = movie_ratings.groupby('title').size().reset_index(name='total_num_ratings')

# Show result
print(movie_rating_counts.head())

                        title  total_num_ratings
0                     #Horror                230
1        (500) Days of Summer                239
2         10 Cloverfield Lane                261
3       10 Days in a Madhouse                254
4  10 Things I Hate About You                252

In [ ]:
# Ensure 'num-rating' is numeric
movie_ratings['num-rating'] = pd.to_numeric(movie_ratings['num-rating'], errors='coerce')

# Compute average rating per title
average_rating = movie_ratings.groupby('title', as_index=False)['num-rating'].mean()

# Rename column for clarity
average_rating.rename(columns={'num-rating': 'avg-rating'}, inplace=True)

# Show result
print(average_rating.head())

                        title  avg-rating
0                     #Horror    3.226087
1        (500) Days of Summer    3.330544
2         10 Cloverfield Lane    3.088123
3       10 Days in a Madhouse    2.748031
4  10 Things I Hate About You    2.896825

In [ ]:
movie_rating_list = average_rating.merge(movie_rating_counts, on='title', how='inner')

In [ ]:
top_20 = movie_rating_list[movie_rating_list['total_num_ratings'] > 250].sort_values('avg-rating', ascending=False).head(20)

In [ ]:
top_20

                         title  avg-rating  total_num_ratings
1225               Extreme Ops    3.713208                265
3149                Son of God    3.682353                255
2382       My Bloody Valentine    3.642857                252
2644            Pink Narcissus    3.626866                268
138   A Streetcar Named Desire    3.615385                273
1880                      Jaws    3.605578                251
4349    The Work and the Glory    3.576471                255
2422          Naturally Native    3.560784                255
1816       Inside Llewyn Davis    3.513410                261
2981               Secretariat    3.507812                256
1497              Gosford Park    3.494208                259
902             Daddy Day Care    3.486166                253
3995          The Mighty Ducks    3.451737                259
399                   Bad Boys    3.440945                254
560                 Blue Crush    3.440476                252
205                 Alex Cross    3.432950                261
1807               Indignation    3.423488                281
1678         Horrible Bosses 2    3.420664                271
161           About Last Night    3.414179                268
4165               The Rundown    3.404669                257

# COLLABORATIVE

In [ ]:
merged.head()

,User-ID,Book-Rating,Location,Age,movie_id,title
0,276725,0,"tyler, texas, usa",NaN,5689,The Blue Lagoon
1,276726,5,"seattle, washington, usa",NaN,8849,Alfie
2,276727,0,"h, new south wales, australia",16.0,17820,Show Boat
3,276729,3,"rijeka, n/a, croatia",16.0,6519,The Dukes of Hazzard
4,276729,6,"rijeka, n/a, croatia",16.0,11013,Secretary

only consider those whose total rating are greater than 200 and user has rated more than 50 books

In [ ]:
merged.groupby('User-ID').count()['Book-Rating']

User-ID
2          1
7          1
8         18
9          3
10         2
          ..
278846     2
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 105283, dtype: int64

In [ ]:
x = merged.groupby('User-ID').count()['Book-Rating'] > 200
movie_enthusiast_user = x[x].index
#899 user did more than 200 rating

In [ ]:
filtered_rating = merged[merged['User-ID'].isin(movie_enthusiast_user)]

In [ ]:
print(filtered_rating.columns)

Index(['User-ID', 'Book-Rating', 'Location', 'Age', 'movie_id', 'title'], dtype='object')

In [ ]:
filtered_rating.groupby('title').count()['Book-Rating']

title
#Horror                        96
(500) Days of Summer          113
10 Cloverfield Lane           112
10 Days in a Madhouse         128
10 Things I Hate About You     97
                             ...
[REC]²                        130
eXistenZ                      106
xXx                           105
xXx: State of the Union       118
Æon Flux                       96
Name: Book-Rating, Length: 4800, dtype: int64

In [ ]:
x = filtered_rating.groupby('title').count()['Book-Rating'] > 50
famous_movies = x.index

In [ ]:
final_ratings = filtered_rating[filtered_rating['title'].isin(famous_movies)]

In [ ]:
final_ratings.drop_duplicates

<bound method DataFrame.drop_duplicates of          User-ID  Book-Rating                       Location   Age  movie_id  \
1456      277427           10          gilbert, arizona, usa  48.0      1378
1457      277427            0          gilbert, arizona, usa  48.0     29064
1458      277427            8          gilbert, arizona, usa  48.0      8461
1459      277427            0          gilbert, arizona, usa  48.0       979
1460      277427            0          gilbert, arizona, usa  48.0     55779
...          ...          ...                            ...   ...       ...
1147612   275970            0  pittsburgh, pennsylvania, usa  46.0     91314
1147613   275970            0  pittsburgh, pennsylvania, usa  46.0     13132
1147614   275970            0  pittsburgh, pennsylvania, usa  46.0     10715
1147615   275970            8  pittsburgh, pennsylvania, usa  46.0     13184
1147616   275970            0  pittsburgh, pennsylvania, usa  46.0     10643

                                   title
1456                            Shortbus
1457                      The Omega Code
1458                         Funny Games
1459                        Irreversible
1460                 Final Destination 5
...                                  ...
1147612  Transformers: Age of Extinction
1147613               All the Real Girls
1147614     Looney Tunes: Back in Action
1147615                Bangkok Dangerous
1147616                    Godzilla 2000

[526356 rows x 6 columns]>

In [ ]:
vectors = final_ratings.pivot_table(index='title',columns='User-ID',values='Book-Rating')

vectors.fillna(0, inplace=True)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_score = cosine_similarity(vectors)

In [ ]:
similarity_score

array([[1.        , 0.15913467, 0.17041835, ..., 0.16972758, 0.09923744,
        0.21775202],
       [0.15913467, 1.        , 0.1039602 , ..., 0.07444345, 0.06486214,
        0.22924659],
       [0.17041835, 0.1039602 , 1.        , ..., 0.0685405 , 0.05003679,
        0.1321015 ],
       ...,
       [0.16972758, 0.07444345, 0.0685405 , ..., 1.        , 0.01026917,
        0.1438769 ],
       [0.09923744, 0.06486214, 0.05003679, ..., 0.01026917, 1.        ,
        0.07685662],
       [0.21775202, 0.22924659, 0.1321015 , ..., 0.1438769 , 0.07685662,
        1.        ]])

In [ ]:
def recommend(movie_name) :
   index = np.where(vectors.index==movie_name)[0][0]
   suggestions = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:6]

   for i in suggestions:
     print(vectors.index[i[0]])

In [ ]:
recommend('#Horror')

Bride Wars
Galaxy Quest
Falcon Rising
The Wackness
Lara Croft: Tomb Raider

In [ ]:
recommend('Bride Wars')

#Horror
The Running Man
The Cabin in the Woods
Black Nativity
The Wackness